name: ipsi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.20.2
  provider: ^6.1.5


flutter:
  uses-material-design: true

  assets:
    - assets/images/bottombar/home.png
    - assets/images/bottombar/home_click.png
    - assets/images/bottombar/chatbot_click.png
    - assets/images/bottombar/chatbot.png
    - assets/images/bottombar/curriculum.png
    - assets/images/bottombar/curriculum_click.png
    - assets/images/bottombar/mypage.png
    - assets/images/bottombar/mypage_click.png
    - assets/images/characters/raggy.png
    - assets/images/characters/morrie.png
    - assets/images/characters/dori.png
    - assets/images/characters/norrie.png
    - assets/images/icon/alert.png
    - assets/images/icon/back.png
    - assets/images/icon/cancel.png
    - assets/images/icon/next.png
    - assets/images/icon/search.png
    - assets/images/icon/glass_chat.png
    - assets/images/icon/glass_calendar.png
    - assets/images/icon/kakao.png


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/pretendard_regular.ttf
          weight: 400
        - asset: assets/fonts/pretendard/pretendard_medium.ttf
          weight: 500
        - asset: assets/fonts/pretendard/pretendard_semiBold.ttf
          weight: 600
        - asset: assets/fonts/pretendard/pretendard_bold.ttf
          weight: 700
